export INSTANCE_TYPE="mirror"
export PROJECT="ct-mirror-wosign1"
export REGION="us-central1"
export CLUSTER="ct-mirror-wosign1"
export ZONES="a b c"
export MIRROR_NUM_REPLICAS_PER_ZONE=2
export MIRROR_TARGET_URL="https://ctlog.wosign.com"
export MIRROR_TARGET_PUBLIC_KEY="wosign_1.pem"
export MONITORING="gcm"
