export INSTANCE_TYPE="mirror"
export PROJECT="ct-mirror-puchuangsida1"
export REGION="us-central1"
export CLUSTER="ct-mirror-puchuangsida1"
export ZONES="a b c"
export MIRROR_NUM_REPLICAS_PER_ZONE=2
export MIRROR_TARGET_URL="https://www.certificatetransparency.cn/ct/"
export MIRROR_TARGET_PUBLIC_KEY="puchuangsida_1.pem"
export MONITORING="gcm"
