// Code generated by protoc-gen-go.
// source: proto/api.proto
// DO NOT EDIT!

/*
Package ct is a generated protocol buffer package.

It is generated from these files:
	proto/api.proto
	proto/ct.proto

It has these top-level messages:
	AddChainRequest
	AddChainResponse
	GetSTHResponse
	Base64LeafEntry
	GetEntriesResponse
	GetConsistencyProofResponse
	GetAuditProofResponse
	GetAcceptedRootsResponse
	GetEntryAndProofResponse
	DigitallySigned
	X509ChainEntry
	PreCert
	CertInfo
	PrecertChainEntry
	XJSONEntry
	LogEntry
	LogID
	SctExtension
	SignedCertificateTimestamp
	SignedCertificateTimestampList
	SignedEntry
	TimestampedEntry
	MerkleTreeLeaf
	MerkleAuditProof
	ShortMerkleAuditProof
	LoggedEntryPB
	SthExtension
	SignedTreeHead
	SSLClientCTData
	ClusterNodeState
	ClusterControl
	ClusterConfig
	SequenceMapping
*/
package ct

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// AddChainRequest represents the JSON request body sent to the add-chain CT
// method.
type AddChainRequest struct {
	Chain []string `protobuf:"bytes,1,rep,name=chain" json:"chain,omitempty"`
}

func (m *AddChainRequest) Reset()                    { *m = AddChainRequest{} }
func (m *AddChainRequest) String() string            { return proto.CompactTextString(m) }
func (*AddChainRequest) ProtoMessage()               {}
func (*AddChainRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// AddChainResponse represents the JSON response to the add-chain CT method.
// An SCT represents a Log's promise to integrate a [pre-]certificate into the
// log within a defined period of time.
type AddChainResponse struct {
	SctVersion Version `protobuf:"varint,1,opt,name=sct_version,enum=ct.Version" json:"sct_version,omitempty"`
	Id         string  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Timestamp  uint64  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Extensions string  `protobuf:"bytes,4,opt,name=extensions" json:"extensions,omitempty"`
	Signature  string  `protobuf:"bytes,5,opt,name=signature" json:"signature,omitempty"`
}

func (m *AddChainResponse) Reset()                    { *m = AddChainResponse{} }
func (m *AddChainResponse) String() string            { return proto.CompactTextString(m) }
func (*AddChainResponse) ProtoMessage()               {}
func (*AddChainResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// GetSTHResponse respresents the JSON response to the get-sth CT method
type GetSTHResponse struct {
	TreeSize          uint64 `protobuf:"varint,1,opt,name=tree_size" json:"tree_size,omitempty"`
	Timestamp         uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Sha256RootHash    string `protobuf:"bytes,3,opt,name=sha256_root_hash" json:"sha256_root_hash,omitempty"`
	TreeHeadSignature string `protobuf:"bytes,4,opt,name=tree_head_signature" json:"tree_head_signature,omitempty"`
}

func (m *GetSTHResponse) Reset()                    { *m = GetSTHResponse{} }
func (m *GetSTHResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSTHResponse) ProtoMessage()               {}
func (*GetSTHResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Base64LeafEntry respresents a Base64 encoded leaf entry
type Base64LeafEntry struct {
	LeafInput string `protobuf:"bytes,1,opt,name=leaf_input" json:"leaf_input,omitempty"`
	ExtraData string `protobuf:"bytes,2,opt,name=extra_data" json:"extra_data,omitempty"`
}

func (m *Base64LeafEntry) Reset()                    { *m = Base64LeafEntry{} }
func (m *Base64LeafEntry) String() string            { return proto.CompactTextString(m) }
func (*Base64LeafEntry) ProtoMessage()               {}
func (*Base64LeafEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// GetEntriesReponse respresents the JSON response to the CT get-entries method
type GetEntriesResponse struct {
	Entries []*Base64LeafEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *GetEntriesResponse) Reset()                    { *m = GetEntriesResponse{} }
func (m *GetEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEntriesResponse) ProtoMessage()               {}
func (*GetEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetEntriesResponse) GetEntries() []*Base64LeafEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

// GetConsistencyProofResponse represents the JSON response to the CT get-consistency-proof method
type GetConsistencyProofResponse struct {
	Consistency []string `protobuf:"bytes,1,rep,name=consistency" json:"consistency,omitempty"`
}

func (m *GetConsistencyProofResponse) Reset()                    { *m = GetConsistencyProofResponse{} }
func (m *GetConsistencyProofResponse) String() string            { return proto.CompactTextString(m) }
func (*GetConsistencyProofResponse) ProtoMessage()               {}
func (*GetConsistencyProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// GetAuditProofResponse represents the JSON response to the CT get-audit-proof method
type GetAuditProofResponse struct {
	Hash     []string `protobuf:"bytes,1,rep,name=hash" json:"hash,omitempty"`
	TreeSize uint64   `protobuf:"varint,2,opt,name=tree_size" json:"tree_size,omitempty"`
}

func (m *GetAuditProofResponse) Reset()                    { *m = GetAuditProofResponse{} }
func (m *GetAuditProofResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAuditProofResponse) ProtoMessage()               {}
func (*GetAuditProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// GetAcceptedRootsResponse represents the JSON response to the CT get-roots method.
type GetAcceptedRootsResponse struct {
	Certificates []string `protobuf:"bytes,1,rep,name=certificates" json:"certificates,omitempty"`
}

func (m *GetAcceptedRootsResponse) Reset()                    { *m = GetAcceptedRootsResponse{} }
func (m *GetAcceptedRootsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAcceptedRootsResponse) ProtoMessage()               {}
func (*GetAcceptedRootsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// GetEntryAndProodReponse represents the JSON response to the CT get-entry-and-proof method
type GetEntryAndProofResponse struct {
	LeafInput string   `protobuf:"bytes,1,opt,name=leaf_input" json:"leaf_input,omitempty"`
	ExtraData string   `protobuf:"bytes,2,opt,name=extra_data" json:"extra_data,omitempty"`
	AuditPath []string `protobuf:"bytes,3,rep,name=audit_path" json:"audit_path,omitempty"`
}

func (m *GetEntryAndProofResponse) Reset()                    { *m = GetEntryAndProofResponse{} }
func (m *GetEntryAndProofResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEntryAndProofResponse) ProtoMessage()               {}
func (*GetEntryAndProofResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*AddChainRequest)(nil), "ct.AddChainRequest")
	proto.RegisterType((*AddChainResponse)(nil), "ct.AddChainResponse")
	proto.RegisterType((*GetSTHResponse)(nil), "ct.GetSTHResponse")
	proto.RegisterType((*Base64LeafEntry)(nil), "ct.Base64LeafEntry")
	proto.RegisterType((*GetEntriesResponse)(nil), "ct.GetEntriesResponse")
	proto.RegisterType((*GetConsistencyProofResponse)(nil), "ct.GetConsistencyProofResponse")
	proto.RegisterType((*GetAuditProofResponse)(nil), "ct.GetAuditProofResponse")
	proto.RegisterType((*GetAcceptedRootsResponse)(nil), "ct.GetAcceptedRootsResponse")
	proto.RegisterType((*GetEntryAndProofResponse)(nil), "ct.GetEntryAndProofResponse")
}

var fileDescriptor0 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xd5, 0x66, 0xb3, 0xa0, 0x4c, 0x96, 0x76, 0x71, 0x41, 0x8a, 0xd8, 0x4b, 0x65, 0x71, 0xd8,
	0x53, 0x41, 0x01, 0x2a, 0xe0, 0x56, 0x2a, 0x04, 0x07, 0x0e, 0xa8, 0xa0, 0x5e, 0x2d, 0x63, 0x4f,
	0x89, 0x25, 0x9a, 0x04, 0x7b, 0x82, 0x68, 0x7f, 0x3d, 0xb6, 0x53, 0x1a, 0x85, 0x13, 0xb7, 0xf8,
	0xcd, 0xbc, 0x0f, 0x3f, 0x07, 0xa6, 0xad, 0x6d, 0xa8, 0x79, 0x26, 0x5b, 0xb3, 0x88, 0x5f, 0x2c,
	0x51, 0xf4, 0x64, 0xd2, 0x83, 0x8a, 0x7a, 0x8c, 0xcf, 0x61, 0xba, 0xd2, 0x7a, 0x5d, 0x49, 0x53,
	0x6f, 0xf0, 0x67, 0x87, 0x8e, 0xd8, 0x03, 0xb8, 0x52, 0xe1, 0x5c, 0x5c, 0xcc, 0x2f, 0xef, 0x32,
	0x7e, 0x84, 0x9b, 0x61, 0xc3, 0xb5, 0x4d, 0xed, 0x90, 0xcd, 0x21, 0x77, 0x8a, 0xc4, 0x2f, 0xb4,
	0xce, 0x34, 0x61, 0xf1, 0xe2, 0x6e, 0x52, 0xe6, 0x0b, 0xaf, 0xba, 0xed, 0x21, 0x06, 0x90, 0x18,
	0x5d, 0x24, 0x7e, 0x90, 0xb1, 0x87, 0x90, 0x91, 0xd9, 0x7b, 0x69, 0xb9, 0x6f, 0x8b, 0x4b, 0x0f,
	0xa5, 0xcc, 0xcf, 0xf1, 0x37, 0x61, 0x1d, 0x76, 0x5d, 0x91, 0xfe, 0x5d, 0x73, 0xe6, 0x7b, 0x2d,
	0xa9, 0xb3, 0x58, 0x5c, 0x05, 0x88, 0xef, 0x61, 0xf2, 0x01, 0xe9, 0xcb, 0xd7, 0x8f, 0x67, 0xe7,
	0xa0, 0x65, 0x11, 0x85, 0x33, 0x47, 0x8c, 0xbe, 0xe9, 0x58, 0x3e, 0x89, 0x50, 0x01, 0x37, 0xae,
	0x92, 0xe5, 0xab, 0xa5, 0xb0, 0x4d, 0x43, 0xa2, 0x92, 0xae, 0x8a, 0xc6, 0x19, 0xbb, 0x85, 0x59,
	0xe4, 0x57, 0x28, 0xb5, 0x18, 0xec, 0x62, 0x02, 0xfe, 0x06, 0xa6, 0xef, 0xa4, 0xc3, 0xe5, 0xcb,
	0x4f, 0x28, 0x77, 0xef, 0x6b, 0xb2, 0x87, 0x10, 0xf4, 0x87, 0x3f, 0x08, 0x53, 0xb7, 0x1d, 0x45,
	0xc3, 0xec, 0x14, 0xde, 0x4a, 0xa1, 0x25, 0xc9, 0xfe, 0x8e, 0xfc, 0x2d, 0x30, 0x9f, 0x34, 0x70,
	0x0c, 0xba, 0x73, 0xda, 0xa7, 0x70, 0x1f, 0x7b, 0x28, 0x96, 0x99, 0x97, 0xb3, 0xd0, 0xd1, 0x3f,
	0x1e, 0xbc, 0x84, 0x5b, 0xcf, 0x5d, 0x7b, 0x86, 0x71, 0xbe, 0x13, 0x75, 0xf8, 0xec, 0x53, 0xef,
	0xce, 0x22, 0x33, 0xc8, 0xd5, 0x30, 0x3b, 0xbd, 0xca, 0x6b, 0x78, 0xec, 0x39, 0xab, 0x4e, 0x1b,
	0x1a, 0x6f, 0x5f, 0x43, 0x1a, 0xaf, 0x1b, 0xd7, 0xc6, 0x75, 0xc5, 0x6e, 0xf8, 0x73, 0x28, 0x02,
	0x53, 0x29, 0x6c, 0x09, 0xf5, 0xc6, 0xf7, 0x33, 0xe4, 0x7d, 0x04, 0xd7, 0x0a, 0x2d, 0x99, 0x9d,
	0x51, 0x92, 0x4e, 0xa1, 0x33, 0xbe, 0x8d, 0x8c, 0x98, 0x75, 0x55, 0xeb, 0xb1, 0xdd, 0x7f, 0xf6,
	0x13, 0x30, 0x19, 0xc2, 0x8a, 0x56, 0x52, 0x78, 0x0b, 0xaf, 0xfb, 0xed, 0x5e, 0xfc, 0x05, 0x5f,
	0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x6c, 0x45, 0x54, 0xa9, 0x02, 0x00, 0x00,
}
